@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": false,
    "cutConstructors": false
  },
  "graphTraversal": {
    "forwardDepth": 999,
    "backwardDepth": 0,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": false,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 4,
    "showDetailedClassStructure": true
  },
  "rootClass": "ru.paulrwd.basepatterns.creational.factory.Program",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_790392457 { 
   	label=paulrwd
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1405034443 { 
   	label=basepatterns
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_557907635 { 
   	label=creational
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   subgraph cluster_165370519 { 
   	label=factory
	labeljust=l
	fillcolor="#bababa"
	style=filled
   
   CppDeveloper768294078[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CppDeveloper</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ writeCode()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CppDeveloperFactory768294078[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CppDeveloperFactory</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createDeveloper(): Developer</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Developer768294078[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)Developer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ writeCode()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

DeveloperFactory768294078[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)DeveloperFactory</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createDeveloper(): Developer</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

JavaDeveloper768294078[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)JavaDeveloper</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ writeCode()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

JavaDeveloperFactory768294078[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)JavaDeveloperFactory</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createDeveloper(): Developer</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PhpDeveloper768294078[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PhpDeveloper</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ writeCode()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PhpDeveloperFactory768294078[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PhpDeveloperFactory</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createDeveloper(): Developer</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Program768294078[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Program</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># createDeveloperBySpecialty(specialty: String): DeveloperFactory</TD></TR>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 
} 
} 

'edges    
Developer768294078 -> CppDeveloper768294078[arrowhead=none, arrowtail=empty, dir=both];
Developer768294078 -> JavaDeveloper768294078[arrowhead=none, arrowtail=empty, dir=both];
Developer768294078 -> PhpDeveloper768294078[arrowhead=none, arrowtail=empty, dir=both];
DeveloperFactory768294078 -> CppDeveloperFactory768294078[arrowhead=none, arrowtail=empty, dir=both];
DeveloperFactory768294078 -> JavaDeveloperFactory768294078[arrowhead=none, arrowtail=empty, dir=both];
DeveloperFactory768294078 -> PhpDeveloperFactory768294078[arrowhead=none, arrowtail=empty, dir=both];
Program768294078 -> Developer768294078[label="main() -> writeCode()"];
Program768294078 -> DeveloperFactory768294078[label="main() -> createDeveloper()"];
    
}
@enduml